### PR TITLE
fix basic generators

### PR DESCRIPTION
**Pull request by kylemac**
a couple things needed fixing:
- you were using `.decapitalize()` which isn't a function that underscore.string gives us, so i switched to the regular `toLowerCase()` function native to JS
- `utils.url` isn't an object that sprout gives us, it's either `utils.src` or `utils.target`
- i don't know if that `${}` interpolation would have worked, but i switched it over to the regular old `+` concatenation  
- you were attempting to write in directories that [likely] weren't there. we've talked about writing directories recursively but we haven't gotten to that feature yet - https://github.com/carrot/sprout/issues/82 . for now, I just added the basic dirs to your `/root` so that when you generate the project, those folders are ready

### CODE REVIEW

**Comment by nanotime** [comment]
Pfff "url" there is the problem! I don't know what im thinking, sure a fingertip missing or something.

Thanks kyle, as you can see, i'm a noob.

**Comment by kylemac** [comment]
no worries, we're here to help :two_men_holding_hands:

**Comment by nanotime** [comment]
hey hey: [decapitalize underscore.string](http://epeli.github.io/underscore.string/#decapitalize-string-gt-string) LOL <3

**Comment by kylemac** [comment]
i stand corrected!

**Comment by nanotime** [comment]
anyway, thanks for all @kylemac, i really appreciate that.

Now i'm going to make a serious sprout template to use.

**Comment by kylemac** [comment]
you're welcome. ping me when you've got one you want to share!

**Pull request merged**
